apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app 
    spec:
      containers:
      - name: react-app
        image: cyberslot/react-app:latest
        # resources:
          # requests:
        #     # memory: "10Mi"
        #     cpu: "25m"
        #   limits:
        #     memory: "500Mi"
        #     cpu: "50m"
        ports:
        - containerPort: 3000
        