apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app 
    spec:
      containers:
      - name: react-app
        # -- Minikube --
        # image: cyberslot/react-app:latest
        # -- GKE --
        image: europe-docker.pkg.dev/web-project-init/eu.gcr.io/react-app:latest
        resources:
          requests:
            memory: "50Mi"
            cpu: "25m"
          limits:
            memory: "100Mi"
            cpu: "50m"
        ports:
        - containerPort: 3000
      # -- GKE part --
      # tolerations:
      # - key: instance_type
      #   value: spot
      #   effect: NoSchedule
      #   operator: Equal
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: team
      #           operator: In
      #           values:
      #           - devops
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #     - labelSelector:
      #         matchExpressions:
      #         - key: app
      #           operator: In
      #           values:
      #           - nginx
      #       topologyKey: kubernetes.io/hostname